language: node_js
notifications:
  email: false
import:
  - source: trevtrich/.travis-ci:github-token-env.yml
before_script: npm ls --production >/dev/null
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
deploy:
- provider: heroku
  api_key:
    secure: QQ/8YfU3E5nFpTpegbr73Nyqc7QnlDxmDXwAOdE/QF7edsZ+VM7mbbIAGbkEWgFczq4DbhohfftyLQ+zWyPuqZ7yl2xTtdxfGKBYj+sJKia1hESiOeYArRBArV8y5aVsZIywoBsQprtE6SGR5Dpbz0HL6KDLjflPGNtl61BzH1GaBk4sVl3iHlgX88Me7mInDq7uXIZm1qAzug0JQLUis8KssSUSDyY3cPY3Xj+a+DLysFiSj2IwpbAr57bstauQF4VDh27qWg88k/tL6f/1R7eBIrGelhoIZGv8LInsVHtv+liMpp0KxM06Z/IBmBWLrBhZLbrl0O9/wya4jJZDYXSAynZI/n3OYzqQ5xVfGA6UCnLpMfjmi79/1pzvrMWWhdBq+GVZUReC5tL1iWmR/AVZZjX+5OrrHJR+/ISNtwROjFIU2bXU4BmXMSmYe/ECrbb+L1Zu1m2Wv3AMT6aJKqYtILk/WFtqZnpjLdjI1iWfnl42KG+LNiTXFLbrhHnFcVtkGSNsnfp5W12ouVHfY/kfb9dRNtA/3q4KlbH1cEEqkHZkoVzKNGfbD3mJekN8WRohETuaSsnxLIA0nulTK4pBFVIVXT3Wu5aZVofNolR4li2cHetndzFkYE8nMG6sdy6P9JX7WQNCaJTDRpysI0jL7JEPS5UwsJboVl38n4k=
  app: greenkeeper-keeper-trevtrich
  on:
    repo: trevtrich/greenkeeper-keeper
after_success: ./scripts/tag.sh
