language: node_js
notifications:
  email: false
before_script: npm ls --production >/dev/null
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
deploy:
- provider: heroku
  api_key:
    secure: CGaV5Tp50NhirbYoR5ybmW/jBif7T2m+HLjZv25Vy1jaOueMmIKhlhjB3lx2GBUo6+cogVMqijWE95jshBryYKStfDo8cQy7B979sV3JzPNloyG335kQhD9MGmRV9EGm1yz/3uwZ6Xl1KbCjyrxeyUZIp7YBnF856g8QKeyfei1rxV5N7i1RxqpG2O5XWRFJzQJOD2Fk6ILwwRBf9ZMOk8ug68Fz3GbfHUZxLK/khPSjLZaoH/wazkkLb0MvMNSqa5HjTas6VBnorn19ahNhZUEhPqj6/N+j8EENpeulVSZDBslnoYKK4Ms2BVr0ju0kdUGHqNbEOq05rIM8XaDxZRf9g5nlOBUjBZJwLofpPB/o5GG37aP6nnBfanpWSIni+M+74L4UaMuWY2j35OjKNOjxTOFkI+7Dz6JMurdt3ZPPzR32BgOHYYUH8UbgpcbHzEmEjPOuC6e4KVWfPl84U7EygOz6Rol8LvrS0Cp2VJ/N2XBuYnSvpfLXlo1XBEJcPPFZEzZYdlF7VXy9BYaGFK8z8wEzDBaPUWQI9pDCh/g+lnIKLE0sbppduQbudW4AgMTfG1Nb9OvXiL2dEMMUAncyMqWl1G4efu9VrP1qI/TbQhaYzjJRcUSKdYOww2K4yX6oGLytJv9w9Gr2p29bLkf9EVxi83lb84xRIMUC1AU=
  app: greenkeeper-keeper-trevtrich
  on:
    repo: trevtrich/greenkeeper-keeper
after_success: ./scripts/tag.sh
env:
  global:
    secure: Isljp/xqMfXv5rWh1jM6orlWffBjUlV0yI35w7VEUD9AiVJQ0ygCI55au9a982UWfhT6yNrZeN+zokh8SzG/9KYtPAB07GmTqz/pFGGPdeoIMhPYeBX9iW3rEwKTn9/Q4gGADm6AY3ZEbhR1xeS9ZhsGVk3Ih2vJDlJ+nbUEUc7irMBwXdV+bKIO150Mm7Z2f7OUER5Y8l+Z5dw+OFsTXvhBQ1HXa0TxKM3Iult3a/Vysq7ZC77seCUKDBVXBjnX+tkCS9+dX3Pfuh8GNSDycj6mu/+3f8bwRYkJxEAxJhmtN88yAFCSYWxeLIdekYGf34lzxRP4zBnW3kS7WUaJQ3RuUBW50C6EHDvkMLVlbtghImBeXCiqLxPxtpbn5vaqvyGaoIUqV2Qom6L9zEsd/W0MlQnqaIjD8efAaHzQB8+mot2xW0Ymz45DS0GMpkRLCzzlVUb5dI1zgdNvxBQc5DfL8x+Md+9RGGYOWETf7APJ7xxhGDCzkbHhjH1L8hgQjSfi0vl0UhE5q+KJZGwpI/1XbNoP8kjz2i+yNeXcWOz2rt9XQhIar46wqOCDo5TEN5HEvOGj6YmkqrJuKMPxfkI1EaM3JgdtGCzZrDQpo/f6LHkZE5lQL7ITx5XfcLOacaH9FTF8V+aBfL8rf6Xg6dBKosAi3YUqX6Sl6NGVz1k=
