language: node_js
notifications:
  email: false
before_script: npm ls --production >/dev/null
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
deploy:
- provider: heroku
  api_key:
    secure: CGaV5Tp50NhirbYoR5ybmW/jBif7T2m+HLjZv25Vy1jaOueMmIKhlhjB3lx2GBUo6+cogVMqijWE95jshBryYKStfDo8cQy7B979sV3JzPNloyG335kQhD9MGmRV9EGm1yz/3uwZ6Xl1KbCjyrxeyUZIp7YBnF856g8QKeyfei1rxV5N7i1RxqpG2O5XWRFJzQJOD2Fk6ILwwRBf9ZMOk8ug68Fz3GbfHUZxLK/khPSjLZaoH/wazkkLb0MvMNSqa5HjTas6VBnorn19ahNhZUEhPqj6/N+j8EENpeulVSZDBslnoYKK4Ms2BVr0ju0kdUGHqNbEOq05rIM8XaDxZRf9g5nlOBUjBZJwLofpPB/o5GG37aP6nnBfanpWSIni+M+74L4UaMuWY2j35OjKNOjxTOFkI+7Dz6JMurdt3ZPPzR32BgOHYYUH8UbgpcbHzEmEjPOuC6e4KVWfPl84U7EygOz6Rol8LvrS0Cp2VJ/N2XBuYnSvpfLXlo1XBEJcPPFZEzZYdlF7VXy9BYaGFK8z8wEzDBaPUWQI9pDCh/g+lnIKLE0sbppduQbudW4AgMTfG1Nb9OvXiL2dEMMUAncyMqWl1G4efu9VrP1qI/TbQhaYzjJRcUSKdYOww2K4yX6oGLytJv9w9Gr2p29bLkf9EVxi83lb84xRIMUC1AU=
  app: greenkeeper-keeper-trevtrich
  on:
    repo: trevtrich/greenkeeper-keeper
after_success: ./scripts/tag.sh
env:
  global:
    secure: ItJdCyx4t4cn4ZUYLrFxP3My22eyl8p7zu7BnrCx1+aKgT7k5ELZa9M6U5Jd55lPCm7LijSh3d54BniADRgC5YomhLR5OikuCbwAloZjc9maPDdzunbK8Z5U+YD1ki4oV73pX3b6UzAc04tqaCMV+2UCrIZnDtuHzNAiAhSHw/C1oXOPMHxShFriSUy9awVBxY/UIhkBcRbOzXL71ye6Z7c8q6M8Ytx2A5pouUKcfDpspFCVljhUQksxe8k0AUlwcqH7FA5fBuSHHS7qegx5/PaJ3xtTCCTe+5XEZQLKM5yh8p7FYEl+4/nM1wc6gR4jqJOZXy1yuTAjb1U/20uOPbWAszGe2MxlqYsX1l0LpfqrflZgzPtTjMl+3qi9HrQoZGt16bt8MpVQ8vet3m+3iGS7u8EXp64Vp4taiTWg8MLfi6mtImiGho2KoGyGnP2yKsxR+Iz/D2GbH2C226TpAUmnCRRh9HHiiA1cVsk8+V9oeAburrgANxK76QsYqx8VfiTwPnjtS8efYT/6sUUhfMe7lpQumE1AwQXNQN95gDq5fqQIOO+KRknOXwFw1eljpfN1cYq2rTdERTnPtrDBAKa57Es5K1FMEAxGQIeUoCyC17ZFLgQ1mSqueiZeXE/PXkugQYrdcpLgbGMAmgMW2hVbLjm/bzgg+cby7qVZzB4=
